new homebrew-based bashrc

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -1,31 +1,44 @@
-function latest_version () {
-  /usr/bin/ls -d $1/*/ | tail -n 1
-}
-PROG_PREFIX=${HOME}/.local/progs
-
-# function to detect the latest version if there are several in a dir
-latest_version_dir() {
-  echo $(ls -d $1/*/ | tail -n 1)
-}
-
-# needed if module command not available
-if ! command -v module &> /dev/null
-then
-  export MODULE_BASHRC_INIT=''
+# set name of shell being used
+SHELLNAME=$(basename ${SHELL})
+# set vars for homebrew itself
+export HOMEBREW_NO_ANALYTICS=1
+if ! [[ -v HOMEBREW_PREFIX ]]; then
+    # variable unset; we auto-detect
+    if [[ -d "/opt/homebrew" ]]; then
+        HOMEBREW_PREFIX="/opt/homebrew"
+    elif [[ -d "${HOME}/.homebrew" ]]; then
+        HOMEBREW_PREFIX="${HOME}/.homebrew"
+    else
+        echo "HOMEBREW_PREFIX not set and can't auto-detect"
+        exit 1
+    fi
 fi
-if [ -z "$MODULE_BASHRC_INIT" ]; then
-  export MODULE_BASHRC_INIT=1
-  # load all the standard module in sticky fashion
-  . ${PROG_PREFIX}/lmod/lmod/init/bash
-  module load home/std
+eval "$(${HOMEBREW_PREFIX}/bin/brew shellenv)"
+
+# source lmod if is installed
+# same for bash end zsh
+LMOD_INIT_SCRIPT=${HOMEBREW_PREFIX}/opt/lmod/init/profile
+if [[ -f ${LMOD_INIT_SCRIPT} ]]; then
+    source ${LMOD_INIT_SCRIPT}
+else
+    echo "${LMOD_INIT_SCRIPT} not found."
+fi
+# add some module paths if they are present
+if [[ -d "${HOME}/modules" ]]; then
+    MODULEPATH="${HOME}/modules${MODULEPATH:+":$MODULEPATH"}"
+fi
+if [[ -d "/opt/modules" ]]; then
+    MODULEPATH="/opt/modules${MODULEPATH:+":$MODULEPATH"}"
 fi
 
-# add .local to path and for libs
-PATH=${HOME}/.local/bin${PATH:+:${PATH}}
-LD_LIBRARYPATH=${HOME}/.local/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
 
+##############################################################
 # Command that should be applied only for interactive shells.
+# are listed below here
+#############################################################
 [[ $- == *i* ]] || return
+
+# some settings for history
 HISTFILESIZE=100000
 HISTSIZE=10000
 
@@ -35,36 +48,57 @@ shopt -s extglob
 shopt -s globstar
 shopt -s checkjobs
 
-alias dtask='task -t ~/.config/go-task/Taskfile.yml'
-alias e='$EDITOR `fzf -m --preview="bat --color always {}"`'
-
-
 # ensure CTRL-S doesn't block the terminal
 if [[ -t 0 && $- = *i* ]]
 then
   stty -ixon
 fi
 
+# default editor
 export EDITOR="nvim";
+
+# on python startup sourced
 export PYTHONSTARTUP=~/.config/python/pythonrc.py
 
-STARSHIP_PREFIX=$(latest_version ${PROG_PREFIX}/starship)
-STARSHIP_BINARY=${STARSHIP_PREFIX}/bin/starship
-if [[ -f ${STARSHIP_BINARY} ]]; then
-  if [[ $TERM != "dumb" && (-z $INSIDE_EMACS || $INSIDE_EMACS == "vterm") ]]; then
-    eval "$(${STARSHIP_PREFIX}/bin/starship init bash --print-full-init)"
-  fi
-fi
 
-ATUIN_PREFIX=$(latest_version ${PROG_PREFIX}/atuin)
-ATUIN_BINARY=${ATUIN_PREFIX}/bin/atuin
-if [[ -f ${ATUIN_BINARY} ]]; then
-  . ${ATUIN_PREFIX}/shell/bash-preexec.sh
-  . ${ATUIN_PREFIX}/shell/atuin_init.sh
+# setup for atuin in case of bash
+# source bash-preexec if homebrew is installed
+# and we are using bash
+if [[ ${SHELLNAME} == "bash" ]]; then
+    PREEXEC_INIT_SCRIPT=${HOMEBREW_PREFIX}/etc/profile.d/bash-preexec.sh 
+    if [[ -f ${PREEXEC_INIT_SCRIPT} ]]; then
+        source ${PREEXEC_INIT_SCRIPT}
+    else
+        echo "${PREEXEC_INIT_SCRIPT} not found."
+    fi
 fi
+eval "$(atuin init ${SHELLNAME})"
 
-ZOXIDE_PREFIX=$(latest_version ${PROG_PREFIX}/zoxide)
-ZOXIDE_BINARY=${ZOXIDE_PREFIX}/bin/zoxide
-if [[ -f ${ZOXIDE_BINARY} ]]; then
-  . ${ZOXIDE_PREFIX}/shell/zoxide_init.sh
-fi
+eval "$(zoxide init ${SHELLNAME})"
+eval "$(starship init ${SHELLNAME})"
+eval "$(micromamba shell hook -s ${SHELLNAME})"
+
+# source an env file
+function dotenv { 
+    set -a; . ${1:-.env} || true; set +a; 
+}; 
+export -f dotenv
+
+###############################
+# Aliases
+###############################
+# lazygit
+alias lg='lazygit'
+
+# lsd
+alias ls='lsd -F'
+alias ll='lsd -lahF'
+alias lt='lsd -lahF --tree'
+alias lt2='lsd -lahF --tree --depth 2'
+alias lt3='lsd -lahF --tree --depth 3'
+
+# default taskfile
+alias dtask='task -t ~/.config/go-task/Taskfile.yml'
+# open editor with fzf search enabled
+alias e='$EDITOR `fzf -m --preview="bat --color always {}"`'
+
